name: Deploy $connect Lambda
on:
  pull_request:
    branches: [ main ]
    paths: [ 'connect/**' ]
  push:
    branches: [ main ]
    paths: [ 'connect/**' ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      FUNCTION_NAME: "YourConnectLambdaName"   # replace with actual $connect Lambda name
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r "connect/requirements.txt" -r "connect/requirements-dev.txt"

      - name: Run unit tests (with coverage)
        run: pytest connect/tests --cov=connect --cov-report=term-missing

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Package and deploy $connect Lambda
        run: |
          cd connect
          zip -r ../connect-deploy.zip . -x "tests/*" -x "requirements*.txt" -x "__pycache__/*"
          aws lambda update-function-code --function-name "$FUNCTION_NAME" --zip-file fileb://connect-deploy.zip